-- Per settlement-date share % for Net profit (junket).
-- Run once on the GD Cage database.

CREATE TABLE IF NOT EXISTS `net_profit_share_percentages` (
  `IDNo` INT NOT NULL AUTO_INCREMENT,
  `SETTLEMENT_DATE` DATE NOT NULL,
  `SHARE_PERCENTAGE` DECIMAL(7,4) NOT NULL DEFAULT 65.0000,
  `ACTIVE` TINYINT NOT NULL DEFAULT 1,
  `ENCODED_BY` INT NULL DEFAULT NULL,
  `ENCODED_DT` DATETIME NULL DEFAULT NULL,
  `EDITED_BY` INT NULL DEFAULT NULL,
  `EDITED_DT` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`IDNo`),
  UNIQUE KEY `uk_net_profit_share_settlement_date` (`SETTLEMENT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
