-- Multipurpose Ledger — money exchange records (separate from money_exchange_transaction).
-- TRANS_TYPE: 1=Deposit, 2=Return
-- Deposit rows link to junket_funds_ledger: LEDGER_ID (ex-currency debit) and CREDIT_LEDGER_ID (in-currency credit).
-- Run once on your MySQL database.

CREATE TABLE IF NOT EXISTS `multipurpose_ledger_exchange` (
  `IDNo` INT NOT NULL AUTO_INCREMENT,
  `LEDGER_ID` INT NULL DEFAULT NULL COMMENT 'junket_funds_ledger.IDNo for deposit rows',
  `TRANS_TYPE` TINYINT NOT NULL COMMENT '1=Deposit, 2=Return',
  `TRANS_DATETIME` DATETIME NOT NULL,
  `ACCOUNT_ID` INT NULL DEFAULT NULL,
  `GUEST_NAME` VARCHAR(255) NULL DEFAULT NULL,
  `REMARK` VARCHAR(500) NULL DEFAULT NULL,
  `IN_CHARGE` VARCHAR(150) NULL DEFAULT NULL,
  `IN_CURRENCY_ID` INT NULL DEFAULT NULL,
  `AMOUNT_IN` DECIMAL(18, 2) NULL DEFAULT NULL,
  `EXCHANGE_CURRENCY_ID` INT NULL DEFAULT NULL,
  `RATE_PERCENT` DECIMAL(18, 4) NULL DEFAULT NULL,
  `EXCHANGE_AMOUNT` DECIMAL(18, 2) NULL DEFAULT NULL,
  `RETURN_AMOUNT` DECIMAL(18, 2) NULL DEFAULT NULL,
  `MARGIN_RETURN` DECIMAL(18, 2) NULL DEFAULT NULL,
  `SOURCE_DEPOSIT_ID` INT NULL DEFAULT NULL COMMENT 'multipurpose_ledger_exchange.IDNo',
  `ENCODED_BY` INT NULL DEFAULT NULL,
  `ENCODED_DT` DATETIME NULL DEFAULT NULL,
  `EDITED_BY` INT NULL DEFAULT NULL,
  `EDITED_DT` DATETIME NULL DEFAULT NULL,
  `ACTIVE` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`IDNo`),
  KEY `idx_mple_active_dt` (`ACTIVE`, `TRANS_DATETIME`),
  KEY `idx_mple_ledger_id` (`LEDGER_ID`),
  KEY `idx_mple_source_deposit` (`SOURCE_DEPOSIT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
